# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


# matrix ====

r:
  - oldrel
  - devel
os:
  - linux
  - osx

node_js:
  - "lts/*"

# matrix ====
matrix:
  fast_finish: true
  allow_failures:
  - r: devel

# general settings ====

warnings_are_errors: true

cache:
  packages: yes
  directories:
    - $HOME/bin


notifications:
  email: false


# linux stuff ====

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev


# macOS stuff ====

disable_homebrew: false

brew_packages:
  - pandoc

git:
  # accio submodule is used only for deploy, so skip generally
  submodules: false
  depth: 3

jobs:
  include:
  - stage: deploy
    os: osx
    r: oldrel
    env: DEPLOY = true
    script:
    - |
      # auth machine for github to get accio submodule
      echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
      git submodule update --init
      R CMD INSTALL .

      # run test coverage
      Rscript -e 'install.packages("covr")'
      Rscript -e 'covr::codecov()'

      # make website
      Rscript -e 'install.packages("pkgdown")'
      Rscript -e 'pkgdown::build_site()'

      # prepare shiny
      Rscript -e 'install.packages("rsconnect")'
      npm install netlify-cli -g
      # repeated install is necessary, because packrat otherwise does not know where pensieve came from
      Rscript -e 'install.packages("devtools")'
      Rscript -e "devtools::install_github(repo = 'maxheld83/pensieve', force = TRUE, ref = '${TRAVIS_BRANCH}')"
      Rscript -e "rsconnect::setAccountInfo(name='maxheld83', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"

    deploy:
    # accio
    - provider: script
      script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio')"
      skip_cleanup: true
      on:
        branch: master
    - provider: script
      script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio-${TRAVIS_BRANCH}')"
      skip_cleanup: true
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH != master"

    # _site
    - provider: script
      script: netlify deploy -s pensieve.netlify.com -t ${NETLIFY_PAT} -e production
      skip_cleanup: true
      on:
        branch: master
    - provider: pages
      github_token: $GITHUB_PAT
      local_dir: docs/
      skip_cleanup: true
      on:
        branch: dev
