# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: FALSE
cache:
  packages: yes
  directories:
    - $HOME/bin

warnings_are_errors: true

script:
  - pwd

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
