# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
sudo: false

before_script:
  - chmod +x ./book/_build.sh
  - chmod +x ./book/_deploy.sh

script:
  - ./book/_build.sh
  - ./book/_deploy.sh

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
