# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: FALSE
cache:
  packages: yes
  directories:
    - $HOME/bin

warnings_are_errors: true

# in here, by default R is built and checked

# now we build the gitbook, by using before_deploy b/c that would cause an error out
before_deploy:
  - R script -e 'setwd(dir = "book/")'
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
