# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

dist:
  - trusty
  - precise

sudo: false

matrix:
  allow_failures:
    - os: osx

cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/docs/book/_bookdown_files

warnings_are_errors: true

disable_homebrew: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated openssl || brew upgrade openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated pandoc || brew upgrade pandoc; fi

before_script:
  - R CMD INSTALL .
  - Rscript -e 'blogdown::install_hugo()'

# here comes the R CMD check (part of the script by default)

after_success:
  - Rscript -e 'covr::codecov()'

jobs:
  include:
    - stage: render
      script: Rscript -e 'pensieve:::render_site2()'
      os: linux
      r: release
    - stage: deploy
      script: docs/_deploy.sh
      os: linux
      r: release

notifications:
  email: false
  slack: sozhoh:P4zamVjBWAc8J0DpwsOyCiqC

addons:
  apt:
    packages:
      - pdf2svg
