# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


# matrix ====

r:
  - oldrel
  - devel
os:
  - linux
  - osx
env:
  # default to no deploy for all matrix cells
  DEPLOY=false

node_js:
  - "lts/*"

matrix:
  fast_finish: true
  include:
  # only deploy this matrix cell...
  - r: oldrel
    os: linux
    env: DEPLOY=true
  exclude:
  # ... but don't do it twice
  - r: oldrel
    os: linux
    env: DEPLOY=false
  allow_failures:
  - r: devel

# general settings ====

warnings_are_errors: true

cache:
  packages: yes
  directories:
    - $HOME/bin


notifications:
  email: false


# linux stuff ====

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev


# macOS stuff ====

disable_homebrew: false

brew_packages:
  - pandoc


# INSTALL ====
# part of R default

git:
  # accio submodule is used only for deploy, so skip generally
  submodules: false

# SCRIPT ====
# part of r default

# all in the below would fail the build (not if done via after_success or after_script, so this is better)
before_deploy:
  # auth machine for github to get accio submodule
  - echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
  - git submodule update --init
  - R CMD INSTALL .
  - Rscript -e 'install.packages("pkgdown")'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
  - npm install netlify-cli -g
  - Rscript -e "devtools::install_github(repo = 'maxheld83/pensieve', force = TRUE, ref = '${TRAVIS_BRANCH}')"
  - Rscript -e "rsconnect::setAccountInfo(name='maxheld83', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"

deploy:
  # accio
  - provider: script
    script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio')"
    skip_cleanup: true
    on:
      branch: master
      condition: "$DEPLOY = true"
  - provider: script
    script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio-${TRAVIS_BRANCH}')"
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$DEPLOY = true && $TRAVIS_BRANCH != master"

  # _site
  - provider: script
    script: netlify deploy -s pensieve.netlify.com -t ${NETLIFY_PAT} -e production
    skip_cleanup: true
    on:
      branch: master
      condition: "$DEPLOY = true"
  - provider: pages
    github_token: $GITHUB_PAT
    local_dir: docs/
    skip_cleanup: true
    on:
      branch: dev
      condition: "$DEPLOY = true"
