# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: FALSE
cache:
  packages: yes
  directories:
    - $HOME/bin

warnings_are_errors: true

before_script:
  - R CMD INSTALL .
  - cd book
  - "[ ! -z \"$BUILD_ALL\" ] && make all || make gitbook"
  - cd ../..

# here comes the R CMD check (part of the script by default)

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
