# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: FALSE
cache:
  packages: yes
  directories:
    - $HOME/bin

warnings_are_errors: true

before_script:
  - R CMD INSTALL .
  - Rscript -e 'setwd(dir = "book/")' -e "render_book(input = "index.Rmd", output_format = c("gitbook", "pdf_book", "epub_book"), output_dir = "../_book")"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
