# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: FALSE
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/book/_bookdown_files

warnings_are_errors: true

before_script:
  - R CMD INSTALL .
  - Rscript -e "render_site2(output_format = "all")"

# here comes the R CMD check (part of the script by default)

after_success:
  - Rscript -e 'covr::codecov()'
  - book/_deploy.sh

notifications:
  email: false
