# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


# matrix ====

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

# general settings ====

warnings_are_errors: false

cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/docs/book/_bookdown_files


notifications:
  email: false


# linux stuff ====

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev


# macOS stuff ====

disable_homebrew: false

brew_packages:
  - openssl
  - pandoc


# INSTALL ====
# part of R default

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
  - git submodule update --init

# SCRIPT ====
# part of r default

# remember that after_success and after_script stages do not fail the build, but before_deploy does, so that is better suited

before_deploy:
  - R CMD INSTALL .
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'pensieve:::render_site2()'
  - npm install netlify-cli -g
  - Rscript -e "devtools::install_github(repo = 'maxheld83/pensieve', force = TRUE, ref = '${TRAVIS_BRANCH}')"
  - Rscript -e "rsconnect::setAccountInfo(name='maxheld83', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"

deploy:
  # accio
  - provider: script
    script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio')"
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release"
  - provider: script
   script: Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio-${TRAVIS_BRANCH}')"
     skip_cleanup: true
     on:
       all_branches: true
       condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release && $TRAVIS_BRANCH != master"

  # _site
  - provider: script
    script: netlify deploy -s pensieve.netlify.com -t ${NETLIFY_PAT} -e production
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release"
  - provider: pages
    github_token: $GITHUB_PAT
    local_dir: _site/
    skip_cleanup: true
    on:
      branch: dev
      condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release"
