# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

r:
- oldrel
- release
- devel

language: r
sudo: FALSE
dist: trusty
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/docs/book/_bookdown_files

warnings_are_errors: true

before_script:
  - R CMD INSTALL .
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'pensieve:::render_site2()'

# here comes the R CMD check (part of the script by default)

after_success:
  - Rscript -e 'covr::codecov()'
  - docs/_deploy.sh

notifications:
  email: false
  slack: sozhoh:P4zamVjBWAc8J0DpwsOyCiqC

addons:
  apt:
    packages:
      - pdf2svg
